CREATE TABLE borrowing_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    lending_organization_id BIGINT NOT NULL,
    borrowing_organization_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    reviewed_by_user_id BIGINT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    purpose VARCHAR(500) NOT NULL,
    start_date DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPROVED', 'DENIED', 'CANCELLED', 'RETURNED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    returned_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_borrowing_request_item
        FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id),
    CONSTRAINT fk_borrowing_request_lender
        FOREIGN KEY (lending_organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_borrowing_request_borrower
        FOREIGN KEY (borrowing_organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_borrowing_request_requested_by
        FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_borrowing_request_reviewed_by
        FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_borrowing_request_dates
        CHECK (due_date >= start_date),
    CONSTRAINT chk_borrowing_request_different_organizations
        CHECK (lending_organization_id <> borrowing_organization_id)
);

CREATE INDEX idx_borrowing_request_lender_status
    ON borrowing_requests(lending_organization_id, status);

CREATE INDEX idx_borrowing_request_borrower_status
    ON borrowing_requests(borrowing_organization_id, status);

CREATE INDEX idx_borrowing_request_item_status
    ON borrowing_requests(inventory_item_id, status);
